/**
 * MongoDB Atlas Vector Search — Voyage AI Setup Playground
 * ─────────────────────────────────────────────────────────
 * Run this in the VS Code MongoDB extension (connected to your Atlas cluster).
 *
 * Steps covered here:
 *  1. Switch to the correct database
 *  2. Create the Atlas Vector Search index on the `tasks` collection
 *  3. Verify the index was created
 *
 * NOTE: Embedding generation is done server-side via the Node.js helper
 *       at backend/helpers/embeddings.js using the voyage-large-2 model.
 *       This playground only manages the MongoDB side of the pipeline.
 */

// ── 1. Use the correct database ──────────────────────────────────────────────
use('rbac_db');

// ── 2. Verify the tasks collection exists ────────────────────────────────────
db.getCollectionNames();

// ── 3. Create Atlas Vector Search Index ──────────────────────────────────────
// Run this ONCE in the Atlas UI or via the Atlas CLI.
// Go to: Atlas → Your Cluster → Search → Create Search Index → JSON Editor
//
// Index Name : task_vector_index
// Collection : rbac_db.tasks
// JSON Definition:
// {
//   "fields": [
//     {
//       "type": "vector",
//       "path": "embedding",
//       "numDimensions": 1024,
//       "similarity": "cosine"
//     },
//     {
//       "type": "filter",
//       "path": "owner"
//     },
//     {
//       "type": "filter",
//       "path": "isDeleted"
//     },
//     {
//       "type": "filter",
//       "path": "status"
//     }
//   ]
// }

// ── 4. Sample Vector Search Query ────────────────────────────────────────────
// Replace <QUERY_EMBEDDING> with an actual 1024-dim array generated by:
//   const { embedText } = require('./helpers/embeddings');
//   const vector = await embedText("find high priority bugs", "query");
//
// db.tasks.aggregate([
//   {
//     $vectorSearch: {
//       index: "task_vector_index",
//       path: "embedding",
//       queryVector: <QUERY_EMBEDDING>,   // 1024-dim array from Voyage AI
//       numCandidates: 100,
//       limit: 5,
//       filter: {
//         isDeleted: { $eq: false },
//       }
//     }
//   },
//   {
//     $project: {
//       _id: 1,
//       title: 1,
//       description: 1,
//       status: 1,
//       priority: 1,
//       score: { $meta: "vectorSearchScore" }
//     }
//   }
// ]);

// ── 5. Inspect a sample task document ────────────────────────────────────────
db.tasks.findOne({}, { title: 1, status: 1, priority: 1, embeddingUpdatedAt: 1 });

// ── 6. Count tasks missing embeddings (need to be re-embedded) ───────────────
db.tasks.countDocuments({ embeddingUpdatedAt: null });
